version: "3.8"
services:
  server:
    build:
      dockerfile: .docker/server/Dockerfile
      context: .
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: .
        target: /server
    command: yarn server